name: Docker Image-Welcome_app(Automate)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rahulr44/welcome_app:latest
    - name: Push the Docker image
      run: docker login -u rahulr44 -p ${{ secrets.DOCKER_TOKEN }} && docker push rahulr44/welcome_app:latest
